[package]
name = "arb_monitoring"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2.0"}
prometheus = "0.14"
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["server", "http1", "http2"] }